apiVersion: v1
kind: Service
metadata:
  name: flask-bookstore-service
spec:
  selector:
    app: flask-bookstore
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort
